// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Kontur")]
[assembly: AssemblyProduct("Kontur")]
[assembly: AssemblyDescription("The message bus library.")]
[assembly: AssemblyVersion("0.2.0")]
[assembly: AssemblyFileVersion("0.2.0")]
[assembly: AssemblyCompany("Mikhail Zabolotko Alex Zaitzev")]
[assembly: AssemblyCopyright("(c) Focus Technologies, 2019")]
[assembly: AssemblyConfiguration("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Kontur";
        internal const System.String AssemblyProduct = "Kontur";
        internal const System.String AssemblyDescription = "The message bus library.";
        internal const System.String AssemblyVersion = "0.2.0";
        internal const System.String AssemblyFileVersion = "0.2.0";
        internal const System.String AssemblyCompany = "Mikhail Zabolotko Alex Zaitzev";
        internal const System.String AssemblyCopyright = "(c) Focus Technologies, 2019";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
